name: RDP

on:
  workflow_dispatch:

jobs:
  secure-rdp:
    runs-on: windows-2022
    timeout-minutes: 360

    steps:
      - name: Configure RDP
        shell: powershell
        run: |
          Set-ItemProperty `
            -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server' `
            -Name 'fDenyTSConnections' `
            -Value 0 `
            -Force

          Set-ItemProperty `
            -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' `
            -Name 'UserAuthentication' `
            -Value 1 `
            -Force

          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

          Restart-Service TermService -Force

      - name: Create RDP User
        shell: powershell
        run: |
          $username = "RDPAdmin47"
          $password = "Vx9!Rdp2026#Qm"

          $securePass = ConvertTo-SecureString `
            $password `
            -AsPlainText `
            -Force

          $existing = Get-LocalUser `
            -Name $username `
            -ErrorAction SilentlyContinue

          if ($existing) {
              Set-LocalUser `
                -Name $username `
                -Password $securePass
          }
          else {
              New-LocalUser `
                -Name $username `
                -Password $securePass `
                -AccountNeverExpires
          }

          Add-LocalGroupMember `
            -Group "Remote Desktop Users" `
            -Member $username `
            -ErrorAction SilentlyContinue

          Write-Host "RDP user created successfully."

      - name: Install Tailscale
        shell: powershell
        run: |
          $installer = "$env:TEMP\tailscale.msi"

          Invoke-WebRequest `
            -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi" `
            -OutFile $installer

          Start-Process `
            msiexec.exe `
            -ArgumentList "/i `"$installer`" /quiet /norestart" `
            -Wait

      - name: Connect Tailscale
        shell: powershell
        env:
          TAILSCALE_AUTH_KEY: ${{ secrets.TAILSCALE_AUTH_KEY }}
        run: |
          if ([string]::IsNullOrWhiteSpace($env:TAILSCALE_AUTH_KEY)) {
              throw "TAILSCALE_AUTH_KEY GitHub Secret missing."
          }

          & "C:\Program Files\Tailscale\tailscale.exe" up `
            --authkey="$env:TAILSCALE_AUTH_KEY"

          & "C:\Program Files\Tailscale\tailscale.exe" status

      - name: Keep Alive
        shell: powershell
        run: |
          while ($true) {
              Start-Sleep -Seconds 300
          }
